#!/bin/bash

# Mensagem sobre o Tempo
mensagem_tempo=""

# Mensagem TXT a ser enviada pelo telegram
mensagem_txt=""

# Aqruivo Json temporario para o clima
JSONFILE="/etc/luna/tmp/${0##*/}.tmp.json"

###########################################
# Tempo
###########################################

rm -rf $JSONFILE
rm -rf $JSONFILE.part

curl -s "http://apiadvisor.climatempo.com.br/api/v1/weather/locale/4290/current?token=32e6ad73da4248ca01a2d358d796b5dc" > $JSONFILE

tempo_graus=$(jq ".data .temperature" <"${JSONFILE}")
cond_tempo=$(jq ".data .condition" <"${JSONFILE}")

mensagem_tempo=$(echo "A temperatura atual é de $tempo_graus graus a condição do tempo para hoje é $cond_tempo." | tr -d '""')

echo $mensagem_tempo

###########################################
# Remove Arquivos temporarios
###########################################
rm -rf $JSONFILE
rm -rf $JSONFILE.part

exit 0